### ISSUE TITLE
Any-Version on npm

### ISSUE THREAD

**Issue by ShimShamSam** [sapics/html-minifier-loader#4]
Is it possible to install the any-version as a dependency? Is it on NPM?

**Comment by sapics** [comment]
Yes it is possible by writing

``` json
"html-minifier-loader": "https://github.com/sapics/html-minifier-loader.git#any-version"
```

in package.json. No npm, now.

**Comment by ShimShamSam** [comment]
Is there a reason it's in a separate branch? Many of the standard loaders for Webpack use the peerDependency pattern. Why lock this particular loader into a specific version?

**Comment by sapics** [comment]
> Many of the standard loaders for Webpack use the peerDependency pattern.

I did not know that. Thanks! I will search them.

> Is there a reason it's in a separate branch?

I am afraid that current user need to fix thier package.json, isn't it?
And, I guess that peerDependency is not necessary in npm3 which is default npm in nodejs 6, isn't it?

**Comment by sapics** [comment]
> I am afraid that current user need to fix thier package.json, isn't it?

I confirmed that it is not necessary by testing.
Thus I will fix. Thanks for your suggestion!

**Comment by sapics** [comment]
@ShimShamSam 
I fixed and published to npm. I fix README as

``` diff
- npm install html-minifier-loader html-minifier
+ npm install html-minifier-loader
```

**Comment by ShimShamSam** [comment]
As long as you bump the major version number, people still using the old version won't have an issue.

**Comment by sapics** [comment]
@ShimShamSam 
As written in #5, it looks better to using previous version (which is not include peerDependencies) in npm 3.
Do you have any better ideas?
