### ISSUE TITLE
Peer Dependency requires adding html-minifier explicitly to package.json

### ISSUE THREAD

**Issue by claywhipkey** [sapics/html-minifier-loader#5]
You made a change on 9/2/2016 that moved html-minifier to a peerDependency. For consumers using npm version 3+ this means html-minifier will not be installed automatically. We have to add it explicitly to our own package.json in order to use html-minifier-loader.

You might want to update the readme.

**Comment by sapics** [comment]
@claywhipkey 
Thank you for the information! I update README in npm.
